---
title: "Data Table"
author: "Anni Liu"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Save and load images
```{r saveimage, eval=FALSE}
image.date <- format(Sys.Date(), "%Y%b%d")
save.image(file = paste0(image.date, "_datatable_image_ALiu.RData"))
```

```{r loadimage}
load("2023Feb11_datatable_image_ALiu.RData")
```


```{r}
library(data.table)
mydt <- fread("2022Dec21_dat_TNBC.csv")
class(mydt) # "data.table" "data.frame"

mydf <- read.csv("2022Dec21_dat_TNBC.csv")
class(mydf) # "data.frame"

mydt2 <- as.data.table(mydf)
class(mydt2)
```


```{r}
str(mydt)
# mydt[i, j, by]
# start with mydt, subset rows using `i`, calculate using `j`, and group by `by`.
```


# Subset the dataset by row
```{r}
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2"]
myRes 

##------Basic operations------
# Select 1st to 6th row
mydt[1:6, ] # Equivalently; mydt[1:6]

# Select the penultimate row
mydt[.N-1]

# Return the number of rows
mydt[, .N]

# Select all rows that have value WA in the column `Race.Ethnicity2`
mydt[Race.Ethnicity2 == "WA"] 

# Select all rows that have value WA and AA in the column `Race.Ethnicity2`
mydt[Race.Ethnicity2 %in% c("WA", "AA")]
```


# Calculate the mean age in the subsetted dataset
```{r}
myRes2 <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", mean(Age.at.Diagnosis, na.rm = T)]
myRes2 # 57.11228

##------Basic operations------
# Return `Clinical.T.Stage2` as a vector
mydt[, Clinical.T.Stage2] 

# Return `Clinical.T.Stage2` and `Race.Ethnicity2` as a data.table
mydt[, .(Clinical.T.Stage2, Race.Ethnicity2)]
# Equivalently
mydt[, list(Clinical.T.Stage2, Race.Ethnicity2)]

# Return the sum of all elements of `Age.at.Diagnosis` in a vector
mydt[, sum(Age.at.Diagnosis)]

# Return the mean of all elements of `Age.at.Diagnosis` and the std. dev. of all elements of `Age.at.Diagnosis` in a data.table
mydt[, .(mean(Age.at.Diagnosis), sd(Age.at.Diagnosis))]
mydt[, .(mean.age = mean(Age.at.Diagnosis), sd.age = sd(Age.at.Diagnosis))]

# Select the `Age.at.Diagnosis` column and compute the std. dev. of all elements of `Age.at.Diagnosis`, which returns a single value and gets recycled
mydt[, .(Age.at.Diagnosis, sd.age = sd(Age.at.Diagnosis))]

# Print the `Age.at.Diagnosis` column and plot the std. dev. of all elements of `Age.at.Diagnosis`
mydt[, .(print(Age.at.Diagnosis), plot(Age.at.Diagnosis))]
```


# Calculate the mean age by Clinical.N.Stage in the subsetted dataset
```{r}
myRes3 <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
               mean(Age.at.Diagnosis, na.rm = T),
               by = Clinical.N.Stage]
myRes3

##------Basic operations------
# Calculate the mean of variable `Age.at.Diagnosis`, grouped by `Clinical.N.Stage` over the subsetted dataset
mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
     mean(Age.at.Diagnosis, na.rm = T),
     by = Clinical.N.Stage]

# Select the Clinical.N.Stage and mean of `Age.at.Diagnosis` where the mean is > 40 over the subsetted dataset (chaining)
mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
     .(mean.age = mean(Age.at.Diagnosis, na.rm = T)),
     by = Clinical.N.Stage][mean.age > 50]

# Calculate the mean of `Age.at.Diagnosis`, grouped by decreasingly ordered `Clinical.N.Stage` over the subsetted dataset
mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
     .(mean.age = mean(Age.at.Diagnosis, na.rm = T)),
     by = Clinical.N.Stage][order(-Clinical.N.Stage)]

# Calculate the mean of `Age.at.Diagnosis`, grouped by each combination of `Clinical.N.Stage` and `ER.LR` over the subsetted dataset
mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
     .(mean.age = mean(Age.at.Diagnosis, na.rm = T)),
     by = .(Clinical.N.Stage, ER.LR)]

# Count the number of rows for every group in Clinical.N.Stage
mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
     .N,
     by = Clinical.N.Stage]
```


# Update columns - `:=`
```{r}
# Update one variable
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
myRes
myRes[, mean.age:=round(mean.age, 2)]
myRes

# Update two variables
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T),
                sd.age = sd(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
myRes
myRes[, c("mean.age", "sd.age"):=list(round(mean.age, 2), round(sd.age, 2))]
myRes
# Alternative way
myRes[, mean.age:= round(mean.age, 2)][, sd.age:=round(sd.age, 2)]
myRes

myRes[, ':='(mean.age=round(mean.age, 2),
             sd.age=round(sd.age, 2))][] # [] Print the result to the screen

# Remove `mean.age`
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T),
                sd.age = sd(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
myRes[, mean.age:=NULL][]

# Remove `mean.age` and `sd.age`
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T),
                sd.age = sd(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
myRes[, c("mean.age", "sd.age"):=NULL][]

myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T),
                sd.age = sd(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
vars.rm=c("mean.age", "sd.age")

# Remove the column with the column name `vars.rm`
myRes[, vars.rm:=NULL][] 

# Remove the columns specified in the variable `vars.rm`
myRes[, (vars.rm):=NULL][] 
```


# `set` family
```{r}
rows <- list(2:3, 4:5)
cols <- 2:3

# Sequence along the values of rows and the values of columns, set the values of those elements as 0
myRes <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
              .(mean.age = mean(Age.at.Diagnosis, na.rm = T),
                sd.age = sd(Age.at.Diagnosis, na.rm = T)),
              by = Clinical.N.Stage]
for (j in c(2L,3L)) set(myRes, j=j, value=NA)
myRes

for(i in seq_along(rows)){ # seq_along(rows) = 1:2
  set(myRes,
      i=rows[[i]], # rows[[1]] = 2,3
      j=cols[i], # cols[1] = 2
      value=rep(c(2:3)))
}
myRes

# Set name of `mean.age` to `Mean.Age`
setnames(myRes, "mean.age", "Mean.Age")
myRes

# Set 2 column names
setnames(myRes, c("mean.age", "sd.age"), c("Mean.Age", "Sd.Age"))
myRes

# Set column orders
setcolorder(myRes, c("sd.age", "mean.age", "Clinical.N.Stage"))
myRes
```


# `.SD` and `.SDcols`
```{r}
# A verbose way to return the whole table
mydt[, .SD] 
identical(mydt, mydt[, .SD])

# A verbose way to select the first and last row 
mydt[, .SD[c(1, .N)]]
identical(mydt[c(1, .N)], mydt[, .SD[c(1, .N)]])

# Calculate the median of each of time to events, grouped by Clinical.N.Stage
mydt[, lapply(.SD, median, na.rm=T), by=Clinical.N.Stage, .SDcols=c("T2LRDeath.ER", "T2LRDeath.PR")]
```


# Index and keys 
```{r}
setkey(myRes,Clinical.N.Stage)

# Return all rows where the key column of `Clinical.N.Stage` has the value N0
myRes["N0"] 

# Return all rows where the key column of `Clinical.N.Stage` has the value N0 or N1
myRes[c("N0","N1")]

setkey(mydt,Clinical.N.Stage)

# Return the first row of all rows that match the value N0 in the key column of `Clinical.N.Stage`
mydt["N0",mult="first"] 

# Return the last row of all rows that match the value N0 in the key column of `Clinical.N.Stage`
mydt["N0",mult="last"] 

# Return the total median of `Age.at.Diagnosis`, for rows of key column `Clinical.N.Stage` that have the value N0
mydt[c("N0"),median(Age.at.Diagnosis)] 

# Return the median of `Age.at.Diagnosis` grouped by `Clinical.N.Stage`
mydt[c("N0", "N1"),.(median.age=median(Age.at.Diagnosis)),by=.EACHI] 

# Sort mydt by `Clinical.N.Stage` and then by `Clinical.T.Stage` within each group of Clinical.N.Stage (invisible)
setkey(mydt,Clinical.N.Stage,Clinical.T.Stage) 
mydt

# Select rows that have the value N3 for the first key (`Clinical.N.Stage`) & the value T4 for the second key (`Clinical.T.Stage`)
mydt[.("N3","T4")] 

# Select rows that have the value N2 or N3 for the first key (`Clinical.N.Stage`) & the value T4 for the second key (`Clinical.T.Stage`)
mydt[.(c("N2","N3"),"T4")] 
```


# Join two data tables
```{r}
myRes4 <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T1|T2", 
               mean(Age.at.Diagnosis, na.rm = T),
               by = Clinical.N.Stage]
myRes4

myRes5 <- mydt[Race.Ethnicity2 == "WA" & Clinical.T.Stage2 == "T3|T4", 
               mean(Age.at.Diagnosis, na.rm = T),
               by = Clinical.N.Stage]
myRes5

setkey(myRes4, "Clinical.N.Stage")
setkey(myRes5, "Clinical.N.Stage")
myRes6 <- myRes4[myRes5]
myRes6 
```
