if (!requireNamespace("easypackages", quietly = TRUE)) {
  install.packages("easypackages")
}
easypackages::libraries("tidyverse", "tidymodels", "modelr", "brms", "tidybayes", "ggdist", "distributional", "ordinal", "ggrepel", "glue", "emmeans"
)
theme_set(theme_tidybayes())

(df_med <- read_csv("./data/medicine.csv", show_col_types = F) |>
  filter(group == 2) |>
  mutate(
    condition = factor(condition), 
    participant_id = paste0("p_", str_pad(row_number(), 2, pad = "0"))) |> # Take the row numbers generated by row_number() and pads them with leading zeros
  select(-group)
)

jitter_set <- position_jitter(height = 0.1, seed = 689) # A random seed to make the jitter reproducible
ggplot(
  data = df_med,
  mapping = aes(x = rank, y = condition)) +     
  geom_point(position = jitter_set, alpha = 0.5, color = "#7c20c1") + 
  scale_x_continuous(breaks = min(df_med$rank):max(df_med$rank))

t_res <- lm(rank ~ -1 + condition, data = df_med) # -1: the output will change the name of base group from (Intercept) to an actual base group name
