if (!requireNamespace("easypackages", quietly = TRUE)) {
  install.packages("easypackages")
}
easypackages::libraries("tidyverse", "tidymodels", "modelr", "brms", "tidybayes", "ggdist", "distributional", "ordinal", "ggrepel", "glue", "emmeans"
)
theme_set(theme_tidybayes())

(df_med <- read_csv("./data/medicine.csv", show_col_types = F) |>
  filter(group == 2) |>
  mutate(
    condition = factor(condition), 
    participant_id = paste0("p_", str_pad(row_number(), 2, pad = "0"))) |> # Take the row numbers generated by row_number() and pads them with leading zeros
  select(-group)
)
